// AUTO-GENERATED by scripts/upload-videos-to-cloudinary.mjs
// Cloudinary CDN Video URLs — q_auto optimized

const cloudinaryVideoUrls = {
  "bgvidieo.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036701/izhaar/video/bgvidieo",
  "song/bg.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036705/izhaar/video/song/bg",
  "video/bg1.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036748/izhaar/video/video/bg1",
  "video/mypage.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036750/izhaar/video/video/mypage",
  "video/reel1.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036752/izhaar/video/video/reel1",
  "video/reel2.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036754/izhaar/video/video/reel2",
  "video/reel3.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036755/izhaar/video/video/reel3",
  "video/reel4.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036757/izhaar/video/video/reel4",
  "video/reel5.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036758/izhaar/video/video/reel5",
  "video/reel6.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036760/izhaar/video/video/reel6",
  "video/reel7.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036761/izhaar/video/video/reel7",
  "video/reel8.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036763/izhaar/video/video/reel8",
  "video/reel9.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036765/izhaar/video/video/reel9",
  "video/Stars_1.mp4": "https://res.cloudinary.com/df5jbm55b/video/upload/q_auto/v1773036768/izhaar/video/video/Stars_1"
};

export default cloudinaryVideoUrls;

export function getCloudVideoUrl(relativePath) {
  return cloudinaryVideoUrls[relativePath] || null;
}
