// AUTO-GENERATED by scripts/upload-to-cloudinary.mjs
// Cloudinary CDN URLs — use these instead of local imports for fast loading
// Format: f_auto,q_auto = auto format + quality per device

const cloudinaryUrls = {
  "cta/boy.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/cta/boy?_a=BAMAOGeA0",
  "cta/girl.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/cta/girl?_a=BAMAOGeA0",
  "Img/crush.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/crush?_a=BAMAOGeA0",
  "Img/gifts.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/gifts?_a=BAMAOGeA0",
  "Img/letter.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/letter?_a=BAMAOGeA0",
  "Img/magazines.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/magazines?_a=BAMAOGeA0",
  "Img/playtogether.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/playtogether?_a=BAMAOGeA0",
  "Img/safedate.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/safedate?_a=BAMAOGeA0",
  "Img/song.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/song?_a=BAMAOGeA0",
  "Img/teleparty.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/teleparty?_a=BAMAOGeA0",
  "Img/trueconnect.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/trueconnect?_a=BAMAOGeA0",
  "Img/website.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Img/website?_a=BAMAOGeA0",
  "Service/connect.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Service/connect?_a=BAMAOGeA0",
  "Service/crush.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Service/crush?_a=BAMAOGeA0",
  "Service/letter.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Service/letter?_a=BAMAOGeA0",
  "Service/song.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Service/song?_a=BAMAOGeA0",
  "testimonials/User1.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/testimonials/User1?_a=BAMAOGeA0",
  "testimonials/User2.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/testimonials/User2?_a=BAMAOGeA0",
  "testimonials/User3.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/testimonials/User3?_a=BAMAOGeA0",
  "testimonials/User4.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/testimonials/User4?_a=BAMAOGeA0",
  "Vectos/1.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/1?_a=BAMAOGeA0",
  "Vectos/10.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/10?_a=BAMAOGeA0",
  "Vectos/11.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/11?_a=BAMAOGeA0",
  "Vectos/12.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/12?_a=BAMAOGeA0",
  "Vectos/13.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/13?_a=BAMAOGeA0",
  "Vectos/2.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/2?_a=BAMAOGeA0",
  "Vectos/3.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/3?_a=BAMAOGeA0",
  "Vectos/4.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/4?_a=BAMAOGeA0",
  "Vectos/5.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/5?_a=BAMAOGeA0",
  "Vectos/6.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/6?_a=BAMAOGeA0",
  "Vectos/7.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/7?_a=BAMAOGeA0",
  "Vectos/8.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/8?_a=BAMAOGeA0",
  "Vectos/9.webp": "https://res.cloudinary.com/df5jbm55b/image/upload/f_auto,q_auto/v1/izhaar/Vectos/9?_a=BAMAOGeA0"
};

export default cloudinaryUrls;

// Helper: get URL by filename (e.g. getCloudUrl('services/songs.webp'))
export function getCloudUrl(relativePath) {
  return cloudinaryUrls[relativePath] || null;
}
